### ISSUE TITLE
启动出错

### ISSUE THREAD

**Issue by laoqijun1** [pchpub/BiliRoaming-Rust-Server#109]
日志
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected usize", line: 136, column: 20)', src/mods/config.rs:54:73
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by pchpub** [comment]
检查配置文件的第136行

**Comment by laoqijun1** [comment]
> 检查配置文件的第136行
默认是这个
  "worker_num": null
要改成什么？

**Comment by cxw620** [comment]
> > 检查配置文件的第136行
> > 默认是这个
> > "worker_num": null
> > 要改成什么？

随便一个正整数, 例如8

**Comment by laoqijun1** [comment]
> > > 检查配置文件的第136行
> > > 默认是这个
> > > "worker_num": null
> > > 要改成什么？
> 
> 随便一个正整数, 例如8

我看看

**Comment by laoqijun1** [comment]
对了问一下，泰国的用户令牌怎么导入进去服务器？

**Comment by laoqijun1** [comment]
可以了
