### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by oneg1** [pchpub/BiliRoaming-Rust-Server#4]
你好喵~
thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:15:63

**Comment by pchpub** [comment]
已修复喵

**Comment by oneg1** [comment]
好了喵，剩下的api是web端搜索要用到的

**Comment by oneg1** [comment]
泰区自定义key后出现
thread 'actix-rt|system:0|arbiter:6' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected `,` or `}`", line: 1, column: 30)', /root/rust/src/mods/get_bili_res.rs:704:79

**Comment by pchpub** [comment]
> 泰区自定义key后出现 thread 'actix-rt|system:0|arbiter:6' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected `,` or `}`", line: 1, column: 30)', /root/rust/src/mods/get_bili_res.rs:704:79

请尝试  `redis-cli GET a41101` 并检查得到的value是否符合json格式

**Comment by oneg1** [comment]
> > 泰区自定义key后出现 thread 'actix-rt|system:0|arbiter:6' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected `,` or `}`", line: 1, column: 30)', /root/rust/src/mods/get_bili_res.rs:704:79
> 
> 请尝试 `redis-cli GET a41101` 并检查得到的value是否符合json格式

![image](https://user-images.githubusercontent.com/31442507/180811030-2843d8b3-3192-4173-a652-75086d30bba8.png)

**Comment by pchpub** [comment]
> > > 泰区自定义key后出现 thread 'actix-rt|system:0|arbiter:6' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected `,` or `}`", line: 1, column: 30)', /root/rust/src/mods/get_bili_res.rs:704:79
> > 
> > 
> > 请尝试 `redis-cli GET a41101` 并检查得到的value是否符合json格式
> 
> ![image](https://user-images.githubusercontent.com/31442507/180811030-2843d8b3-3192-4173-a652-75086d30bba8.png)

看起来格式没问题
使用下面这种格式试试
`SET a41101 "{\"area_num\":4,\"access_key\":\"A23BC4AB4CBAC3BAC94BA32C8BA8CB\",\"refresh_token\":\"B29BC4AB4CBAC3BAC04BA32C9BA8CB\",\"expire_time\":1658726170}"`
注：预期情况下 TYPE a41101 应为 String

**Comment by oneg1** [comment]
![image](https://user-images.githubusercontent.com/31442507/180909152-6d5e15da-988e-4ebc-8d3d-fd3a15e95f7e.png)

**Comment by oneg1** [comment]
> ![image](https://user-images.githubusercontent.com/31442507/180909152-6d5e15da-988e-4ebc-8d3d-fd3a15e95f7e.png)

好像多了 `"`

**Comment by pchpub** [comment]
> 

尝试切换到debug分支，此分支将展示更多有用的信息

**Comment by oneg1** [comment]
> > 
> 
> 尝试切换到debug分支，此分支将展示更多有用的信息 （会显示从redis得到的值，以此来确定是否格式有问题）
![image](https://user-images.githubusercontent.com/31442507/180916459-defacc25-d209-4bf4-b23d-cf4fe55c5d51.png)
猜测是刷新access_key后导致多了 `"` ，这里的access_key已经是刷新之后的了

**Comment by pchpub** [comment]
> > > 
> > 
> > 
> > 尝试切换到debug分支，此分支将展示更多有用的信息 （会显示从redis得到的值，以此来确定是否格式有问题）
> > ![image](https://user-images.githubusercontent.com/31442507/180916752-50cba436-dd79-46ab-bef2-d6be87219d8c.png)
> > 猜测是刷新access_key后导致多了 `"` ，这里的access_key已经是刷新之后的了

已修复

**Comment by oneg1** [comment]
可以观看了，现在字幕还有点问题，提示字幕加载失败，和go版请求的字幕对比，rust的多了个VIP
![image](https://user-images.githubusercontent.com/31442507/180948408-a862b884-53f0-4067-b943-615759791854.png)

**Comment by pchpub** [comment]
> 可以观看了，现在字幕还有点问题，提示字幕加载失败，和go版请求的字幕对比，rust的多了个VIP ![image](https://user-images.githubusercontent.com/31442507/180948408-a862b884-53f0-4067-b943-615759791854.png)

找到原因了（替换的时候字幕id重复了，正在修）ps：那个多出来的vip是泰区api返回自带的

**Comment by pchpub** [comment]
> 可以观看了，现在字幕还有点问题，提示字幕加载失败，和go版请求的字幕对比，rust的多了个VIP ![image](https://user-images.githubusercontent.com/31442507/180948408-a862b884-53f0-4067-b943-615759791854.png)

已修复
