### ISSUE TITLE
[bug] 服务器状态推送功能的一个无伤大雅的bug

### ISSUE THREAD

**Issue by cxw620** [pchpub/BiliRoaming-Rust-Server#47]
在自行添加pushplus推送的功能的时候偶然发现的bug.
![image](https://user-images.githubusercontent.com/70561268/190918826-6a8fc2a1-b54b-4839-bc7b-80f94a2b01cf.png)
这里, 如果请求的host和search remake里面设置的host不一样, 就不插入自定义搜索内容直接return了, 在下面也执行不到在下面的初始化redis的数据的代码了
![image](https://user-images.githubusercontent.com/70561268/190918840-2bba8b5d-8c40-49da-912f-5edf9d507ffa.png)
导致search永远显示不可用

**Comment by pchpub** [comment]
应该修好了（beta分支），更换了下位置。
（在军训所以可能我消息看的不是很及时）

**Comment by cxw620** [comment]
> 应该修好了（beta分支），更换了下位置。 （在军训所以可能我消息看的不是很及时）

OK, 我看看
~~军训? (大一?) 震惊猫猫脸~~
