### ISSUE TITLE
漫游的日志查看为timeout

### ISSUE THREAD

**Issue by hanasaki-misaki** [pchpub/BiliRoaming-Rust-Server#96]
使用CDN进行反代
反代节点直接访问是可以连接的，但是使用BiliRoaming-Rust-Server
就出现服务器不可用
使用bili漫游的日志查看为timeout，也就是请求超时
请问要如何解决？

**Comment by cxw620** [comment]
在修了

**Comment by cxw620** [comment]
> 使用CDN进行反代 反代节点直接访问是可以连接的，但是使用BiliRoaming-Rust-Server 就出现服务器不可用 使用bili漫游的日志查看为timeout，也就是请求超时 请问要如何解决？

在修了在修了

**Comment by cxw620** [comment]
https://github.com/pchpub/BiliRoaming-Rust-Server/suites/10278084412/artifacts/504791537
试试这个最新ci

**Comment by hanasaki-misaki** [comment]
> https://github.com/pchpub/BiliRoaming-Rust-Server/suites/10278084412/artifacts/504791537 试试这个最新ci @hanasaki-misaki

依旧是服务器不可用

**Comment by hanasaki-misaki** [comment]
依旧是服务器不可用，但是漫游日志的timeout无了
@cxw620

**Comment by hanasaki-misaki** [comment]
getContent url: https://api.bilibili.com/pgc/review/user?media_id=28480920&access_key=ed2e938456f18b552d430f908ca08b12
请求变成了向api.bilibili.com发起

**Comment by cxw620** [comment]
> 依旧是服务器不可用，但是漫游日志的timeout无了 并且请求的地址为api.bilibili.com @cxw620

贴服务器debug日志.

参考命令:
+ 先清除服务器redis所有缓存: `redis-cli -h 127.0.0.1 -p 6379 keys "*"| xargs redis-cli  -h 127.0.0.1 -p 6379 del`
+ 然后`systemctl stop biliroaming_rust_server`停掉
+ 然后手动运行服务端, 开启debug日志: `RUST_LOG=debug RUST_BACKTRACE=full ./biliroaming_rust_server`
+ 最后客户端试试, 把服务端产生的日志发一下

**Comment by hanasaki-misaki** [comment]
> > 依旧是服务器不可用，但是漫游日志的timeout无了 并且请求的地址为api.bilibili.com @cxw620
> 
> 贴服务器debug日志.
> 
> 参考命令:
> 
>     * 先清除服务器redis所有缓存: `redis-cli -h 127.0.0.1 -p 6379 keys "*"| xargs redis-cli  -h 127.0.0.1 -p 6379 del`
> 
>     * 然后`systemctl stop biliroaming_rust_server`停掉守护程序
> 
>     * 然后手动运行服务端, 开启debug日志: `RUST_LOG=debug RUST_BACKTRACE=full ./biliroaming_rust_server`
> 
>     * 最后客户端试试, 把服务端产生的日志发一下

手机显示依旧为服务器不可用
RUST_LOG=debug是吧
日志输出到终端嘛？我这没显示
![图片](https://user-images.githubusercontent.com/77177482/211523237-fef21110-abfb-4bf5-a193-5de491e4cf30.png)
手机漫游日志
[log (1) (3).txt](https://github.com/pchpub/BiliRoaming-Rust-Server/files/10381470/log.1.3.txt)

**Comment by cxw620** [comment]
`Failed to connect to api.lolicon.team`
你是在用`api.lolicon.team`这个对吧. 自己检查一下网络环境, 是不是给ADH什么的拦截了. 服务端压根没收到请求()

**Comment by cxw620** [comment]
> > > 依旧是服务器不可用，但是漫游日志的timeout无了 并且请求的地址为api.bilibili.com @cxw620
> > 
> > 
> > 贴服务器debug日志.
> > 参考命令:
> > ```
> > * 先清除服务器redis所有缓存: `redis-cli -h 127.0.0.1 -p 6379 keys "*"| xargs redis-cli  -h 127.0.0.1 -p 6379 del`
> > 
> > * 然后`systemctl stop biliroaming_rust_server`停掉守护程序
> > 
> > * 然后手动运行服务端, 开启debug日志: `RUST_LOG=debug RUST_BACKTRACE=full ./biliroaming_rust_server`
> > 
> > * 最后客户端试试, 把服务端产生的日志发一下
> > ```
> 
> 手机显示依旧为服务器不可用 RUST_LOG=debug是吧 日志输出到终端嘛？我这没显示 ![图片](https://user-images.githubusercontent.com/77177482/211523237-fef21110-abfb-4bf5-a193-5de491e4cf30.png) 手机漫游日志 [log (1) (3).txt](https://github.com/pchpub/BiliRoaming-Rust-Server/files/10381470/log.1.3.txt)

`Failed to connect to api.lolicon.team`
你是在用`api.lolicon.team`这个对吧. 自己检查一下网络环境, 是不是给ADH什么的拦截了. 服务端压根没收到请求()

**Comment by hanasaki-misaki** [comment]
> > > > 依旧是服务器不可用，但是漫游日志的timeout无了 并且请求的地址为api.bilibili.com @cxw620
> > > 
> > > 
> > > 贴服务器debug日志.
> > > 参考命令:
> > > ```
> > > * 先清除服务器redis所有缓存: `redis-cli -h 127.0.0.1 -p 6379 keys "*"| xargs redis-cli  -h 127.0.0.1 -p 6379 del`
> > > 
> > > * 然后`systemctl stop biliroaming_rust_server`停掉守护程序
> > > 
> > > * 然后手动运行服务端, 开启debug日志: `RUST_LOG=debug RUST_BACKTRACE=full ./biliroaming_rust_server`
> > > 
> > > * 最后客户端试试, 把服务端产生的日志发一下
> > > ```
> > 
> > 
> > 手机显示依旧为服务器不可用 RUST_LOG=debug是吧 日志输出到终端嘛？我这没显示 ![图片](https://user-images.githubusercontent.com/77177482/211523237-fef21110-abfb-4bf5-a193-5de491e4cf30.png) 手机漫游日志 [log (1) (3).txt](https://github.com/pchpub/BiliRoaming-Rust-Server/files/10381470/log.1.3.txt)
> 
> `Failed to connect to api.lolicon.team` 你是在用`api.lolicon.team`这个对吧. 自己检查一下网络环境, 是不是给ADH什么的拦截了. 服务端压根没收到请求()

摇人去了，都改成api.lolicon.team
Debug依旧没有东西
倒是有个没啥用的
[2023-01-10 18:35:05][DEBUG] error handling /favicon.ico: No such file or directory (os error 2)
要发他们的日志嘛？

**Comment by cxw620** [comment]
> > > > > 依旧是服务器不可用，但是漫游日志的timeout无了 并且请求的地址为api.bilibili.com @cxw620
> > > > 
> > > > 
> > > > 贴服务器debug日志.
> > > > 参考命令:
> > > > ```
> > > > * 先清除服务器redis所有缓存: `redis-cli -h 127.0.0.1 -p 6379 keys "*"| xargs redis-cli  -h 127.0.0.1 -p 6379 del`
> > > > 
> > > > * 然后`systemctl stop biliroaming_rust_server`停掉守护程序
> > > > 
> > > > * 然后手动运行服务端, 开启debug日志: `RUST_LOG=debug RUST_BACKTRACE=full ./biliroaming_rust_server`
> > > > 
> > > > * 最后客户端试试, 把服务端产生的日志发一下
> > > > ```
> > > 
> > > 
> > > 手机显示依旧为服务器不可用 RUST_LOG=debug是吧 日志输出到终端嘛？我这没显示 ![图片](https://user-images.githubusercontent.com/77177482/211523237-fef21110-abfb-4bf5-a193-5de491e4cf30.png) 手机漫游日志 [log (1) (3).txt](https://github.com/pchpub/BiliRoaming-Rust-Server/files/10381470/log.1.3.txt)
> > 
> > 
> > `Failed to connect to api.lolicon.team` 你是在用`api.lolicon.team`这个对吧. 自己检查一下网络环境, 是不是给ADH什么的拦截了. 服务端压根没收到请求()
> 
> 摇人去了，都改成api.lolicon.team Debug依旧没有东西 倒是有个没啥用的 [2023-01-10 18:35:05][DEBUG] error handling /favicon.ico: No such file or directory (os error 2) 要发他们的日志嘛？

你这就是客户端压根没连上, 关掉代理之类的东西重试, 或者换个设备. 服务端应该是正常的

**Comment by hanasaki-misaki** [comment]
这样的话，该不会是漫游版本导致的吧
因为换成CDN反代节点是正常的，测试也是移动数据，没有私人DNS设置
测试漫游版本为1.6.8、1.6.7

**Comment by hanasaki-misaki** [comment]
> > > > > > 依旧是服务器不可用，但是漫游日志的timeout无了 并且请求的地址为api.bilibili.com @cxw620
> > > > > 
> > > > > 
> > > > > 贴服务器debug日志.
> > > > > 参考命令:
> > > > > ```
> > > > > * 先清除服务器redis所有缓存: `redis-cli -h 127.0.0.1 -p 6379 keys "*"| xargs redis-cli  -h 127.0.0.1 -p 6379 del`
> > > > > 
> > > > > * 然后`systemctl stop biliroaming_rust_server`停掉守护程序
> > > > > 
> > > > > * 然后手动运行服务端, 开启debug日志: `RUST_LOG=debug RUST_BACKTRACE=full ./biliroaming_rust_server`
> > > > > 
> > > > > * 最后客户端试试, 把服务端产生的日志发一下
> > > > > ```
> > > > 
> > > > 
> > > > 手机显示依旧为服务器不可用 RUST_LOG=debug是吧 日志输出到终端嘛？我这没显示 ![图片](https://user-images.githubusercontent.com/77177482/211523237-fef21110-abfb-4bf5-a193-5de491e4cf30.png) 手机漫游日志 [log (1) (3).txt](https://github.com/pchpub/BiliRoaming-Rust-Server/files/10381470/log.1.3.txt)
> > > 
> > > 
> > > `Failed to connect to api.lolicon.team` 你是在用`api.lolicon.team`这个对吧. 自己检查一下网络环境, 是不是给ADH什么的拦截了. 服务端压根没收到请求()
> > 
> > 
> > 摇人去了，都改成api.lolicon.team Debug依旧没有东西 倒是有个没啥用的 [2023-01-10 18:35:05][DEBUG] error handling /favicon.ico: No such file or directory (os error 2) 要发他们的日志嘛？
> 
> 你这就是客户端压根没连上, 关掉代理之类的东西重试, 或者换个设备. 服务端应该是正常的
> 
> 我试了试, 是ok的 ![image](https://user-images.githubusercontent.com/70561268/211533277-8674be61-dda1-4b55-a017-1b9eb2d56b02.png)

换了台手机
[log.txt](https://github.com/pchpub/BiliRoaming-Rust-Server/files/10381955/log.txt)

移动数据
无设置指定DNS

服务器端
![图片](https://user-images.githubusercontent.com/77177482/211536555-bc2a699c-1487-4822-a19d-6cc83dfd8fde.png)

**Comment by cxw620** [comment]
> > > > > > > 依旧是服务器不可用，但是漫游日志的timeout无了 并且请求的地址为api.bilibili.com @cxw620
> > > > > > 
> > > > > > 
> > > > > > 贴服务器debug日志.
> > > > > > 参考命令:
> > > > > > ```
> > > > > > * 先清除服务器redis所有缓存: `redis-cli -h 127.0.0.1 -p 6379 keys "*"| xargs redis-cli  -h 127.0.0.1 -p 6379 del`
> > > > > > 
> > > > > > * 然后`systemctl stop biliroaming_rust_server`停掉守护程序
> > > > > > 
> > > > > > * 然后手动运行服务端, 开启debug日志: `RUST_LOG=debug RUST_BACKTRACE=full ./biliroaming_rust_server`
> > > > > > 
> > > > > > * 最后客户端试试, 把服务端产生的日志发一下
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 手机显示依旧为服务器不可用 RUST_LOG=debug是吧 日志输出到终端嘛？我这没显示 ![图片](https://user-images.githubusercontent.com/77177482/211523237-fef21110-abfb-4bf5-a193-5de491e4cf30.png) 手机漫游日志 [log (1) (3).txt](https://github.com/pchpub/BiliRoaming-Rust-Server/files/10381470/log.1.3.txt)
> > > > 
> > > > 
> > > > `Failed to connect to api.lolicon.team` 你是在用`api.lolicon.team`这个对吧. 自己检查一下网络环境, 是不是给ADH什么的拦截了. 服务端压根没收到请求()
> > > 
> > > 
> > > 摇人去了，都改成api.lolicon.team Debug依旧没有东西 倒是有个没啥用的 [2023-01-10 18:35:05][DEBUG] error handling /favicon.ico: No such file or directory (os error 2) 要发他们的日志嘛？
> > 
> > 
> > 你这就是客户端压根没连上, 关掉代理之类的东西重试, 或者换个设备. 服务端应该是正常的
> > 我试了试, 是ok的 ![image](https://user-images.githubusercontent.com/70561268/211533277-8674be61-dda1-4b55-a017-1b9eb2d56b02.png)
> 
> 换了台手机 [log.txt](https://github.com/pchpub/BiliRoaming-Rust-Server/files/10381955/log.txt)
> 
> 移动数据 无设置指定DNS
> 
> 服务器端 ![图片](https://user-images.githubusercontent.com/77177482/211536555-bc2a699c-1487-4822-a19d-6cc83dfd8fde.png)

一样的问题, 连接超时, 你服务端看看nginx是不是寄了(

**Comment by hanasaki-misaki** [comment]
> 
补充说明

以前解析为`api.lolicon.team`
更换解析为`bili.lolicon.team`
以下为控制台日志
```
[root@email biliRoaming]# RUST_LOG=debug RUST_BACKTRACE=full ./biliroaming_rust_server
[2023-01-10 19:34:07][ INFO] 你好喵~
[2023-01-10 19:34:07][ INFO] Starting 8 workers
[2023-01-10 19:34:07][ INFO] Tokio runtime found; starting in existing Tokio runtime
[2023-01-10 19:34:07][ERROR] Specified path is not a directory: "./web/"
[2023-01-10 19:34:07][ERROR] Specified path is not a directory: "./web/"
[2023-01-10 19:34:07][ERROR] Specified path is not a directory: "./web/"
[2023-01-10 19:34:07][ERROR] Specified path is not a directory: "./web/"
[2023-01-10 19:34:07][ERROR] Specified path is not a directory: "./web/"
[2023-01-10 19:34:07][ERROR] Specified path is not a directory: "./web/"
[2023-01-10 19:34:07][ERROR] Specified path is not a directory: "./web/"
[2023-01-10 19:34:07][ERROR] Specified path is not a directory: "./web/"
[2023-01-10 19:34:18][DEBUG] [GET USER_INFO] UID 347946481 | AK ed2e938456f18b552d430f908ca08b12 | U.VIP true -> Got AK ed2e938456f18b552d430f908ca08b12's user info from cache
[2023-01-10 19:34:28][DEBUG] [GET USER_INFO] UID 347946481 | AK ed2e938456f18b552d430f908ca08b12 | U.VIP true -> Got AK ed2e938456f18b552d430f908ca08b12's user info from cache
[2023-01-10 19:34:51][ERROR] [GET USER_CER_INFO][U] 上游返回好像不是JSON... 是不是没接入公共黑名单?
[2023-01-10 19:34:51][DEBUG] [GET USER_CER_INFO][U] 解析上游返回数据错误: 
[2023-01-10 19:35:00][ERROR] [GET USER_CER_INFO][U] 上游返回好像不是JSON... 是不是没接入公共黑名单?
[2023-01-10 19:35:00][DEBUG] [GET USER_CER_INFO][U] 解析上游返回数据错误: 
[2023-01-10 19:35:10][DEBUG] [GET USER_INFO] UID 347946481 | AK ed2e938456f18b552d430f908ca08b12 | U.VIP true -> Got AK ed2e938456f18b552d430f908ca08b12's user info from cache
[2023-01-10 19:35:20][DEBUG] [GET USER_INFO] UID 347946481 | AK ed2e938456f18b552d430f908ca08b12 | U.VIP true -> Got AK ed2e938456f18b552d430f908ca08b12's user info from cache
[2023-01-10 19:35:41][ERROR] [GET USER_CER_INFO][U] 上游返回好像不是JSON... 是不是没接入公共黑名单?
[2023-01-10 19:35:41][DEBUG] [GET USER_CER_INFO][U] 解析上游返回数据错误: 
[2023-01-10 19:35:52][ERROR] [GET USER_CER_INFO][U] 上游返回好像不是JSON... 是不是没接入公共黑名单?
[2023-01-10 19:35:52][DEBUG] [GET USER_CER_INFO][U] 解析上游返回数据错误: 
[2023-01-10 19:38:42][DEBUG] [UPDATE_CACHE] UID 347946481 | AK 7f58ae762eec34ef8ee791b68f3e1c12 -> is VIP: true. New user_info cache data: {"code":0,"access_key":"7f58ae762eec34ef8ee791b68f3e1c12","uid":347946481,"vip_expire_time":1684512000000,"expire_time":1675510722164}
[2023-01-10 19:38:42][DEBUG] [GET USER_INFO] UID 347946481 | AK 7f58ae762eec34ef8ee791b68f3e1c12 | U.VIP true -> Got AK 7f58ae762eec34ef8ee791b68f3e1c12's user info from upstream
[2023-01-10 19:38:53][DEBUG] [GET USER_INFO] UID 347946481 | AK 7f58ae762eec34ef8ee791b68f3e1c12 | U.VIP true -> Got AK 7f58ae762eec34ef8ee791b68f3e1c12's user info from cache
[2023-01-10 19:39:13][ERROR] [GET USER_CER_INFO][U] 上游返回好像不是JSON... 是不是没接入公共黑名单?
[2023-01-10 19:39:13][DEBUG] [GET USER_CER_INFO][U] 解析上游返回数据错误: 
[2023-01-10 19:39:25][ERROR] [GET USER_CER_INFO][U] 上游返回好像不是JSON... 是不是没接入公共黑名单?
[2023-01-10 19:39:25][DEBUG] [GET USER_CER_INFO][U] 解析上游返回数据错误: 

```

补充第三台设备的日志
```
[root@email biliRoaming]# RUST_LOG=debug RUST_BACKTRACE=full ./biliroaming_rust_server
[2023-01-10 19:47:01][ INFO] 你好喵~
[2023-01-10 19:47:01][ INFO] Starting 8 workers
[2023-01-10 19:47:01][ INFO] Tokio runtime found; starting in existing Tokio runtime
[2023-01-10 19:47:01][ERROR] Specified path is not a directory: "./web/"
[2023-01-10 19:47:01][ERROR] Specified path is not a directory: "./web/"
[2023-01-10 19:47:01][ERROR] Specified path is not a directory: "./web/"
[2023-01-10 19:47:01][ERROR] Specified path is not a directory: "./web/"
[2023-01-10 19:47:01][ERROR] Specified path is not a directory: "./web/"
[2023-01-10 19:47:01][ERROR] Specified path is not a directory: "./web/"
[2023-01-10 19:47:01][ERROR] Specified path is not a directory: "./web/"
[2023-01-10 19:47:01][ERROR] Specified path is not a directory: "./web/"
[2023-01-10 19:47:23][DEBUG] error handling /favicon.ico: No such file or directory (os error 2)
[2023-01-10 19:48:20][DEBUG] [UPDATE_CACHE] UID 23579215 | AK a8029a199c7cae49840cd357ae20e311 -> is VIP: true. New user_info cache data: {"code":0,"access_key":"a8029a199c7cae49840cd357ae20e311","uid":23579215,"vip_expire_time":1691510400000,"expire_time":1675511300424}
[2023-01-10 19:48:20][DEBUG] [GET USER_INFO] UID 23579215 | AK a8029a199c7cae49840cd357ae20e311 | U.VIP true -> Got AK a8029a199c7cae49840cd357ae20e311's user info from upstream
[2023-01-10 19:48:30][DEBUG] [GET USER_INFO] UID 23579215 | AK a8029a199c7cae49840cd357ae20e311 | U.VIP true -> Got AK a8029a199c7cae49840cd357ae20e311's user info from cache
[2023-01-10 19:48:52][ERROR] [GET USER_CER_INFO][U] 上游返回好像不是JSON... 是不是没接入公共黑名单?
[2023-01-10 19:48:52][DEBUG] [GET USER_CER_INFO][U] 解析上游返回数据错误: 
[2023-01-10 19:49:02][ERROR] [GET USER_CER_INFO][U] 上游返回好像不是JSON... 是不是没接入公共黑名单?
[2023-01-10 19:49:02][DEBUG] [GET USER_CER_INFO][U] 解析上游返回数据错误: 
```
以上是服务器端日志
以下是手机日志
第一台手机设备
[log01.txt](https://github.com/pchpub/BiliRoaming-Rust-Server/files/10382337/log01.txt)

第二台手机设备
[log02.txt](https://github.com/pchpub/BiliRoaming-Rust-Server/files/10382345/log02.txt)

第三台手机设备
[log(1).txt](https://github.com/pchpub/BiliRoaming-Rust-Server/files/10382387/log.1.txt)


配置相关
![图片](https://user-images.githubusercontent.com/77177482/211544415-60403d97-fe27-4c46-9454-6e96e4ff7781.png)

**Comment by cxw620** [comment]
> > 
> 
> 补充说明
> 
> 以前解析为`api.lolicon.team` 更换解析为`bili.lolicon.team` 以下为控制台日志
> 
> ```
> [root@email biliRoaming]# RUST_LOG=debug RUST_BACKTRACE=full ./biliroaming_rust_server
> [2023-01-10 19:34:07][ INFO] 你好喵~
> [2023-01-10 19:34:07][ INFO] Starting 8 workers
> [2023-01-10 19:34:07][ INFO] Tokio runtime found; starting in existing Tokio runtime
> [2023-01-10 19:34:07][ERROR] Specified path is not a directory: "./web/"
> [2023-01-10 19:34:07][ERROR] Specified path is not a directory: "./web/"
> [2023-01-10 19:34:07][ERROR] Specified path is not a directory: "./web/"
> [2023-01-10 19:34:07][ERROR] Specified path is not a directory: "./web/"
> [2023-01-10 19:34:07][ERROR] Specified path is not a directory: "./web/"
> [2023-01-10 19:34:07][ERROR] Specified path is not a directory: "./web/"
> [2023-01-10 19:34:07][ERROR] Specified path is not a directory: "./web/"
> [2023-01-10 19:34:07][ERROR] Specified path is not a directory: "./web/"
> [2023-01-10 19:34:18][DEBUG] [GET USER_INFO] UID 347946481 | AK ed2e938456f18b552d430f908ca08b12 | U.VIP true -> Got AK ed2e938456f18b552d430f908ca08b12's user info from cache
> [2023-01-10 19:34:28][DEBUG] [GET USER_INFO] UID 347946481 | AK ed2e938456f18b552d430f908ca08b12 | U.VIP true -> Got AK ed2e938456f18b552d430f908ca08b12's user info from cache
> [2023-01-10 19:34:51][ERROR] [GET USER_CER_INFO][U] 上游返回好像不是JSON... 是不是没接入公共黑名单?
> [2023-01-10 19:34:51][DEBUG] [GET USER_CER_INFO][U] 解析上游返回数据错误: 
> [2023-01-10 19:35:00][ERROR] [GET USER_CER_INFO][U] 上游返回好像不是JSON... 是不是没接入公共黑名单?
> [2023-01-10 19:35:00][DEBUG] [GET USER_CER_INFO][U] 解析上游返回数据错误: 
> [2023-01-10 19:35:10][DEBUG] [GET USER_INFO] UID 347946481 | AK ed2e938456f18b552d430f908ca08b12 | U.VIP true -> Got AK ed2e938456f18b552d430f908ca08b12's user info from cache
> [2023-01-10 19:35:20][DEBUG] [GET USER_INFO] UID 347946481 | AK ed2e938456f18b552d430f908ca08b12 | U.VIP true -> Got AK ed2e938456f18b552d430f908ca08b12's user info from cache
> [2023-01-10 19:35:41][ERROR] [GET USER_CER_INFO][U] 上游返回好像不是JSON... 是不是没接入公共黑名单?
> [2023-01-10 19:35:41][DEBUG] [GET USER_CER_INFO][U] 解析上游返回数据错误: 
> [2023-01-10 19:35:52][ERROR] [GET USER_CER_INFO][U] 上游返回好像不是JSON... 是不是没接入公共黑名单?
> [2023-01-10 19:35:52][DEBUG] [GET USER_CER_INFO][U] 解析上游返回数据错误: 
> [2023-01-10 19:38:42][DEBUG] [UPDATE_CACHE] UID 347946481 | AK 7f58ae762eec34ef8ee791b68f3e1c12 -> is VIP: true. New user_info cache data: {"code":0,"access_key":"7f58ae762eec34ef8ee791b68f3e1c12","uid":347946481,"vip_expire_time":1684512000000,"expire_time":1675510722164}
> [2023-01-10 19:38:42][DEBUG] [GET USER_INFO] UID 347946481 | AK 7f58ae762eec34ef8ee791b68f3e1c12 | U.VIP true -> Got AK 7f58ae762eec34ef8ee791b68f3e1c12's user info from upstream
> [2023-01-10 19:38:53][DEBUG] [GET USER_INFO] UID 347946481 | AK 7f58ae762eec34ef8ee791b68f3e1c12 | U.VIP true -> Got AK 7f58ae762eec34ef8ee791b68f3e1c12's user info from cache
> [2023-01-10 19:39:13][ERROR] [GET USER_CER_INFO][U] 上游返回好像不是JSON... 是不是没接入公共黑名单?
> [2023-01-10 19:39:13][DEBUG] [GET USER_CER_INFO][U] 解析上游返回数据错误: 
> [2023-01-10 19:39:25][ERROR] [GET USER_CER_INFO][U] 上游返回好像不是JSON... 是不是没接入公共黑名单?
> [2023-01-10 19:39:25][DEBUG] [GET USER_CER_INFO][U] 解析上游返回数据错误: 
> ```
> 
> 补充第三台设备的日志
> 
> ```
> [root@email biliRoaming]# RUST_LOG=debug RUST_BACKTRACE=full ./biliroaming_rust_server
> [2023-01-10 19:47:01][ INFO] 你好喵~
> [2023-01-10 19:47:01][ INFO] Starting 8 workers
> [2023-01-10 19:47:01][ INFO] Tokio runtime found; starting in existing Tokio runtime
> [2023-01-10 19:47:01][ERROR] Specified path is not a directory: "./web/"
> [2023-01-10 19:47:01][ERROR] Specified path is not a directory: "./web/"
> [2023-01-10 19:47:01][ERROR] Specified path is not a directory: "./web/"
> [2023-01-10 19:47:01][ERROR] Specified path is not a directory: "./web/"
> [2023-01-10 19:47:01][ERROR] Specified path is not a directory: "./web/"
> [2023-01-10 19:47:01][ERROR] Specified path is not a directory: "./web/"
> [2023-01-10 19:47:01][ERROR] Specified path is not a directory: "./web/"
> [2023-01-10 19:47:01][ERROR] Specified path is not a directory: "./web/"
> [2023-01-10 19:47:23][DEBUG] error handling /favicon.ico: No such file or directory (os error 2)
> [2023-01-10 19:48:20][DEBUG] [UPDATE_CACHE] UID 23579215 | AK a8029a199c7cae49840cd357ae20e311 -> is VIP: true. New user_info cache data: {"code":0,"access_key":"a8029a199c7cae49840cd357ae20e311","uid":23579215,"vip_expire_time":1691510400000,"expire_time":1675511300424}
> [2023-01-10 19:48:20][DEBUG] [GET USER_INFO] UID 23579215 | AK a8029a199c7cae49840cd357ae20e311 | U.VIP true -> Got AK a8029a199c7cae49840cd357ae20e311's user info from upstream
> [2023-01-10 19:48:30][DEBUG] [GET USER_INFO] UID 23579215 | AK a8029a199c7cae49840cd357ae20e311 | U.VIP true -> Got AK a8029a199c7cae49840cd357ae20e311's user info from cache
> [2023-01-10 19:48:52][ERROR] [GET USER_CER_INFO][U] 上游返回好像不是JSON... 是不是没接入公共黑名单?
> [2023-01-10 19:48:52][DEBUG] [GET USER_CER_INFO][U] 解析上游返回数据错误: 
> [2023-01-10 19:49:02][ERROR] [GET USER_CER_INFO][U] 上游返回好像不是JSON... 是不是没接入公共黑名单?
> [2023-01-10 19:49:02][DEBUG] [GET USER_CER_INFO][U] 解析上游返回数据错误: 
> ```
> 
> 以上是服务器端日志 以下是手机日志 第一台手机设备 [log01.txt](https://github.com/pchpub/BiliRoaming-Rust-Server/files/10382337/log01.txt)
> 
> 第二台手机设备 [log02.txt](https://github.com/pchpub/BiliRoaming-Rust-Server/files/10382345/log02.txt)
> 
> 第三台手机设备 [log(1).txt](https://github.com/pchpub/BiliRoaming-Rust-Server/files/10382387/log.1.txt)
> 
> 配置相关
***

把在线黑名单关了, qimo的服务器昨天寄了()
![image](https://user-images.githubusercontent.com/70561268/211551596-b1f13568-bb68-40ed-9c09-caaa6a9709ef.png)

(你的配置图片我给你删了嗷)
